# Generated by Django 6.0.2 on 2026-02-23 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, null=True)),
                ('site_name', models.CharField(max_length=150)),
                ('transmission_media', models.CharField(blank=True, max_length=10, null=True)),
                ('a_end', models.CharField(blank=True, max_length=150, null=True)),
                ('b_end', models.CharField(blank=True, max_length=150, null=True)),
                ('terminal_equipment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('make', models.CharField(blank=True, max_length=80, null=True)),
                ('terminalequipment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('cluster', models.CharField(blank=True, max_length=80, null=True)),
                ('port_2g', models.CharField(blank=True, max_length=30, null=True)),
                ('port_3g', models.CharField(blank=True, max_length=30, null=True)),
                ('port_4g', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transmedia.mediainventory')),
            ],
        ),
    ]
