# Generated by Django 6.0.2 on 2026-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmedia', '0004_rename_spare_diversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversiondmw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sparedmw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sparedmw',
            name='stored',
            field=models.CharField(blank=True, choices=[('BSS_STORE', 'BSS Store'), ('IN_SITE', 'In site'), ('DIVERTED', 'Diverted')], max_length=20, null=True),
        ),
    ]
