# Generated by Django 6.0.2 on 2026-02-22 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('site_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bss_incharge_name', models.CharField(blank=True, max_length=120, null=True)),
                ('bss_incharge_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('technician_name', models.CharField(blank=True, max_length=120, null=True)),
                ('technician_mobile', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('eb_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dg_kwh_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hour_meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dg_status', models.CharField(blank=True, choices=[('auto', 'Auto'), ('manual', 'Manual'), ('faulty', 'Faulty')], max_length=10, null=True)),
                ('dg_remarks', models.TextField(blank=True, null=True)),
                ('dc_load_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('powerplant_max_modules', models.IntegerField(blank=True, null=True)),
                ('modules_total', models.IntegerField(blank=True, null=True)),
                ('modules_working', models.IntegerField(blank=True, null=True)),
                ('modules_faulty', models.IntegerField(blank=True, null=True)),
                ('modules_spare', models.IntegerField(blank=True, null=True)),
                ('battery_backup_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discharge_test_conducted', models.BooleanField(blank=True, null=True)),
                ('cleanliness_of_battery', models.CharField(blank=True, choices=[('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True)),
                ('aviation_lamp_condition', models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working'), ('not_available', 'Not Available')], max_length=20, null=True)),
                ('fire_extinguisher_condition', models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working'), ('not_available', 'Not Available')], max_length=20, null=True)),
                ('aircondition_status', models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working'), ('not_available', 'Not Available')], max_length=20, null=True)),
                ('free_cooling_status', models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working'), ('not_available', 'Not Available')], max_length=20, null=True)),
                ('overall_site_cleanliness', models.CharField(blank=True, choices=[('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='utility.site')),
            ],
        ),
        migrations.CreateModel(
            name='DieselFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_filling', models.DateField()),
                ('balance_on_tank', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diesel_filled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hour_meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_after_filling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diesel_fillings', to='utility.site')),
            ],
        ),
    ]
