# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utility", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaInventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(max_length=200)),
                (
                    "terminal_equipment",
                    models.CharField(choices=[("MAAN", "MAAN"), ("DMW", "DMW"), ("CPAN", "CPAN")], max_length=10),
                ),
                ("make", models.CharField(max_length=100)),
                ("terminalequipment_id", models.CharField(blank=True, max_length=400, unique=True)),
                ("cluster", models.CharField(blank=True, max_length=100, null=True)),
                ("port_2g", models.CharField(blank=True, max_length=50, null=True)),
                ("port_3g", models.CharField(blank=True, max_length=50, null=True)),
                ("port_4g", models.CharField(blank=True, max_length=50, null=True)),
                ("transmission_media", models.CharField(choices=[("OF", "OF"), ("DMW", "DMW")], max_length=10)),
            ],
        ),
    ]
