# Generated by Django 6.0.2 on 2026-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='aircondition_status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('both_ac_working', 'BOTH AC are working'), ('not_working', 'Not Working'), ('not_available', 'Not Available')], max_length=20, null=True),
        ),
    ]
