# Generated by Django 6.0.2 on 2026-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_inspection_aircondition_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='contract_demand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='diesel_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='power_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
