# Generated by Django 6.0.2 on 2026-02-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_inspection_contract_demand_inspection_diesel_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='aircondition_status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('both_ac_working', 'BOTH AC are working'), ('not_working', 'Not Working'), ('not_available', 'Not Available'), ('na_outdoor_site', 'Not Applicable(OUTDOOR SITE)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='fire_extinguisher_condition',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working'), ('not_available', 'Not Available'), ('na_outdoor_site', 'Not Applicable(OUTDOOR SITE)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='free_cooling_status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working'), ('not_available', 'Not Available'), ('na_outdoor_site', 'Not Applicable(OUTDOOR SITE)')], max_length=20, null=True),
        ),
    ]
