# Generated by Django 6.0.2 on 2026-02-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_alter_inspection_aircondition_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='spare_unused_items_available',
            field=models.TextField(blank=True, null=True),
        ),
    ]
